"""add TodoTask model

Revision ID: d000a7bf758a
Revises:
Create Date: 2024-06-02 00:29:21.277756

"""

from typing import Sequence, Union

import sqlalchemy as sa

# FIXME: mypy doesn't understand alembic imports
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "d000a7bf758a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_tasks",
        sa.Column("title", sa.Text(), nullable=False, comment="Title of the task"),
        sa.Column("description", sa.Text(), nullable=False, comment="Description of the task"),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", name="todostatus"),
            server_default="PENDING",
            nullable=False,
            comment="Status of the task",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todo_tasks")
    # ### end Alembic commands ###
